// Single-Spa-BySystem/micro-app-vue3/src/App.vue
<template>
  <h3>Micro-App-Vue3</h3>
  <div>
    <router-link to="/">首页</router-link>
    <router-link to="/about">关于</router-link>
  </div>
  <router-view></router-view>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "App",
});
</script>

// Single-Spa-BySystem/micro-app-react/src/App.tsx
import React from "react";
import {
  BrowserRouter,
  Routes,
  Route,
  NavLink,
} from "react-router-dom";
import Home from "./Home";
import About from "./About";

function App(props: any) {
  console.log("Micro-App-React props",props);
  const Router = BrowserRouter;
  return (
    <Router basename={"/"}>
      <NavLink to="/">首页</NavLink>
      <NavLink to="/about">关于</NavLink>
      <Routes>
        <Route path="/" element={<Home />}></Route>
        <Route path="/about" element={<About />}></Route>
      </Routes>
    </Router>
  );
}

export default App;
