// Single-Spa-BySystem/main-app-react/src/App.tsx
import React from "react";
import {
  BrowserRouter,
  Routes,
  Route,
  NavLink,
  HashRouter,
} from "react-router-dom";
import Home from "./Home";
import Content from "./Content";

function App(props: any) {
  console.log("Micro-App-React props", props);
  const { base, mode } = props;
  const Router = mode === "history" ? BrowserRouter : HashRouter;
  return (
    <Router basename={base}>
      <h3>Main-App-React 基座Demo</h3>
      <NavLink to="/">首页</NavLink>
      <NavLink to="/content/">内容</NavLink>
      <Routes>
        <Route path="/" element={<Home />}></Route>
        <Route path="/content/*" element={<Content />}></Route>
      </Routes>
    </Router>
  );
}

export default App;

// Single-Spa-BySystem/main-app-vue3/src/App.vue
<template>
  <div>Main-App-Vue3 基座Demo</div>
  <div>
    <router-link to="/">首页</router-link>
    <router-link to="/content">内容</router-link>
  </div>
  <router-view></router-view>
</template>

<script lang="ts">
import { AppProps } from "single-spa";
import { defineComponent, PropType, ref } from "vue";

export default defineComponent({
  name: "App",
  props: {
    base: String,
    mode: String,
    name: String,
    mountParcel: Function as PropType<AppProps["mountParcel"]>,
    singleSpa: Object as PropType<AppProps["singleSpa"]>,
  },
  setup(props) {
    console.log("Main-App-Vue3 Props", props);
  },
});
</script>

<style scoped></style>
